const app = document.querySelector("#app");
const state = { user: null, page: "dashboard", instances: [], selected: null, console: [], workshop: [], rotation: { cycle: [], queue: [] }, runtime: {}, modules: null, notices: [], configPath: "game/csgo/cfg/server.cfg", language: localStorage.getItem("cs2webui-language") || "en" };
const labels = {
  dashboard: "Dashboard", instances: "Servers", console: "Console",
  workshop: "Workshop", rotation: "Rotation", plugins: "Plugins",
  players: "Players", config: "Configuration", maintenance: "Maintenance", users: "Users",
};
const optionalPages = { dashboard: "dashboard", workshop: "workshop-library", rotation: "visual-map-rotation", players: "advanced-players" };
const ru = {
  Dashboard: "\u0414\u0430\u0448\u0431\u043e\u0440\u0434", Servers: "\u0421\u0435\u0440\u0432\u0435\u0440\u044b", Console: "\u041a\u043e\u043d\u0441\u043e\u043b\u044c", Workshop: "Workshop",
  Rotation: "\u0420\u043e\u0442\u0430\u0446\u0438\u044f", Plugins: "\u041f\u043b\u0430\u0433\u0438\u043d\u044b", Players: "\u0418\u0433\u0440\u043e\u043a\u0438", Configuration: "\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f", Maintenance: "\u041e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u0435", Users: "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438",
  "Log out": "\u0412\u044b\u0439\u0442\u0438", "Sign in": "\u0412\u043e\u0439\u0442\u0438", Username: "\u041b\u043e\u0433\u0438\u043d", Password: "\u041f\u0430\u0440\u043e\u043b\u044c", Role: "\u0420\u043e\u043b\u044c", Name: "\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435",
  "Server overview": "\u041e\u0431\u0437\u043e\u0440 \u0441\u0435\u0440\u0432\u0435\u0440\u043e\u0432", Instances: "\u0418\u043d\u0441\u0442\u0430\u043d\u0441\u044b", "Free disk space": "\u0421\u0432\u043e\u0431\u043e\u0434\u043d\u043e \u043d\u0430 \u0434\u0438\u0441\u043a\u0435", "Available RAM": "\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u0430\u044f RAM", "Host load": "\u041d\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0445\u043e\u0441\u0442\u0430",
  "Isolated servers": "\u0418\u0437\u043e\u043b\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0441\u0435\u0440\u0432\u0435\u0440\u044b", "Create instance": "\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0438\u043d\u0441\u0442\u0430\u043d\u0441", "Refresh runtime": "\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u043c\u0435\u0442\u0440\u0438\u043a\u0438", "Install / validate": "\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c / \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c", Start: "\u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c", Stop: "\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c", Clone: "\u041a\u043b\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u0442\u044c", "Remove entry": "\u0423\u0431\u0440\u0430\u0442\u044c \u0437\u0430\u043f\u0438\u0441\u044c", "Delete files": "\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0444\u0430\u0439\u043b\u044b",
  "Persistent cycle": "\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u0446\u0438\u043a\u043b", "One-time queue": "\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f \u043e\u0447\u0435\u0440\u0435\u0434\u044c", "Rotation history": "\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0440\u043e\u0442\u0430\u0446\u0438\u0438", "Skip to next": "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043a \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0439", "Export JSON": "\u042d\u043a\u0441\u043f\u043e\u0440\u0442 JSON", Restore: "\u0412\u043e\u0441\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c", Remove: "\u0423\u0431\u0440\u0430\u0442\u044c",
  "Install built-in bridge": "\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c bridge", Install: "\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c", Enable: "\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c", Disable: "\u0412\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c", "Create backup": "\u0421\u043e\u0437\u0434\u0430\u0442\u044c backup", "Save policy": "\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043e\u043b\u0438\u0442\u0438\u043a\u0443", "Create account": "\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0443\u0447\u0435\u0442\u043d\u0443\u044e \u0437\u0430\u043f\u0438\u0441\u044c",
  "Linux control panel": "\u041f\u0430\u043d\u0435\u043b\u044c \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f Linux", "Sign in to continue": "\u0412\u043e\u0439\u0434\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c", "UDP port": "UDP-\u043f\u043e\u0440\u0442", "Start map": "\u0421\u0442\u0430\u0440\u0442\u043e\u0432\u0430\u044f \u043a\u0430\u0440\u0442\u0430", Preset: "\u041f\u0440\u0435\u0441\u0435\u0442", "Install source": "\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0444\u0430\u0439\u043b\u043e\u0432", "RCON password": "\u041f\u0430\u0440\u043e\u043b\u044c RCON",
  "Apply preset live": "\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u0440\u0435\u0441\u0435\u0442 \u0441\u0435\u0439\u0447\u0430\u0441", Execute: "\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", "Save quick command": "\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0431\u044b\u0441\u0442\u0440\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", Add: "\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", "Use command": "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u043a\u0430\u0440\u0442\u0443", "Import collection": "\u0418\u043c\u043f\u043e\u0440\u0442 \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438", "Cache preview locally": "\u041a\u044d\u0448\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043f\u0440\u0435\u0432\u044c\u044e \u043b\u043e\u043a\u0430\u043b\u044c\u043d\u043e",
  "Manual title fallback": "\u0417\u0430\u043f\u0430\u0441\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435", "Manual HTTPS preview fallback": "\u0417\u0430\u043f\u0430\u0441\u043d\u0430\u044f HTTPS-\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u0440\u0435\u0432\u044c\u044e", "Add to cycle": "\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432 \u0446\u0438\u043a\u043b", "Queue map": "\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432 \u043e\u0447\u0435\u0440\u0435\u0434\u044c", "Import JSON": "\u0418\u043c\u043f\u043e\u0440\u0442 JSON", Backups: "\u0420\u0435\u0437\u0435\u0440\u0432\u043d\u044b\u0435 \u043a\u043e\u043f\u0438\u0438",
  "Scheduled restart notice": "\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0435 \u043e \u043f\u043b\u0430\u043d\u043e\u0432\u043e\u043c \u0440\u0435\u0441\u0442\u0430\u0440\u0442\u0435", "Restart every minutes": "\u0420\u0435\u0441\u0442\u0430\u0440\u0442 \u043a\u0430\u0436\u0434\u044b\u0435 N \u043c\u0438\u043d\u0443\u0442", "Notify before minutes": "\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u044f\u0442\u044c \u0437\u0430 N \u043c\u0438\u043d\u0443\u0442", "Maximum defer minutes": "\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u043e\u0442\u0441\u0440\u043e\u0447\u043a\u0430", "Update before restart": "\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u043f\u0435\u0440\u0435\u0434 \u0440\u0435\u0441\u0442\u0430\u0440\u0442\u043e\u043c", "Defer while players are online": "\u041e\u0442\u043b\u043e\u0436\u0438\u0442\u044c, \u0435\u0441\u043b\u0438 \u0435\u0441\u0442\u044c \u0438\u0433\u0440\u043e\u043a\u0438", "Backup before update": "\u0421\u043e\u0437\u0434\u0430\u0442\u044c backup \u043f\u0435\u0440\u0435\u0434 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435\u043c",
  "Run maintenance now": "\u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0439\u0447\u0430\u0441",
  "Preview diff": "\u041f\u0440\u0435\u0434\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 diff", "Apply with backup": "\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c \u0441 backup", "Audit log": "\u0416\u0443\u0440\u043d\u0430\u043b \u0434\u0435\u0439\u0441\u0442\u0432", "Local accounts": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u0443\u0447\u0435\u0442\u043d\u044b\u0435 \u0437\u0430\u043f\u0438\u0441\u0438",
};
function tr(value) { return state.language === "ru" ? (ru[value] || value) : value; }
function localizeHtml(html) { return Object.entries(ru).reduce((value, [en, translated]) => value.replaceAll(`>${en}<`, `>${translated}<`), html); }

async function api(path, options = {}) {
  const response = await fetch(path, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  if (response.status === 401) { renderLogin(); throw new Error("Authentication required"); }
  if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.detail || "Request failed"); }
  return response.status === 204 ? null : response.json();
}
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]); }
function expectedStandardMap(command) { return command?.startsWith("changelevel ") ? command.slice("changelevel ".length) : null; }
function hasModule(id) { return (state.modules || []).some((item) => item.id === id); }
function isAdmin() { return state.user?.role === "admin"; }
function canOperate() { return isAdmin() || state.user?.role === "operator"; }
function isPageVisible(id) { return (!optionalPages[id] || hasModule(optionalPages[id])) && (id !== "users" || isAdmin()) && (id !== "console" || canOperate()); }
function visibleLabels() { return Object.entries(labels).filter(([id]) => isPageVisible(id)); }
function selectedInstance() { return state.instances.find((item) => item.id === state.selected) || state.instances[0]; }
function button(label, action, kind = "ghost") { return `<button class="button ${kind}" data-action="${action}" type="submit">${escapeHtml(tr(label))}</button>`; }
function shell(body) {
  const moduleLinks = (state.modules || []).filter((item) => item.ui_path).map((item) => `<button class="nav-button ${state.page === `module:${item.id}` ? "active" : ""}" data-page="module:${escapeHtml(item.id)}">${escapeHtml(item.navigation_label || item.name)}</button>`).join("");
  const title = state.page.startsWith("module:") ? (state.modules || []).find((item) => `module:${item.id}` === state.page)?.navigation_label : labels[state.page];
  const notices = state.notices.map((item) => `<div class="notice"><strong>Scheduled restart:</strong> ${escapeHtml(item.instance_name)} · ${escapeHtml(new Date(item.next_run_at).toLocaleString())}</div>`).join("");
  app.innerHTML = `<div class="control-shell"><aside class="control-nav"><div class="brand"><div class="brand-mark">C2</div><div><strong>CS2 WebUI</strong><span>${tr("Linux control panel")}</span></div></div><nav class="nav-links">${visibleLabels().map(([id, label]) => `<button class="nav-button ${state.page === id ? "active" : ""}" data-page="${id}">${tr(label)}</button>`).join("")}${moduleLinks}</nav><div class="nav-footer"><span class="user-chip">${escapeHtml(state.user.username)} · ${escapeHtml(state.user.role)}</span></div></aside><section class="control-content"><header class="control-topbar"><div><span class="eyebrow">CS2 WEBUI</span><h1>${escapeHtml(tr(title || "Module"))}</h1></div><div class="toolbar"><button class="button ghost" data-action="language" type="button">${state.language === "ru" ? "EN" : "RU"}</button>${button("Log out", "logout")}</div></header>${notices}<section>${localizeHtml(body)}</section></section></div>`;
  app.querySelectorAll("[data-page]").forEach((item) => item.addEventListener("click", () => { state.page = item.dataset.page; render(); }));
  app.querySelector('[data-action="logout"]').addEventListener("click", async () => { await api("/api/auth/logout", { method: "POST" }); state.user = null; state.modules = null; renderLogin(); });
  app.querySelector('[data-action="language"]').addEventListener("click", () => { state.language = state.language === "ru" ? "en" : "ru"; localStorage.setItem("cs2webui-language", state.language); render(); });
}
function renderLogin(error = "") {
  app.innerHTML = `<div class="login-shell"><form class="login-box"><div class="brand"><div class="brand-mark">C2</div><div><strong>CS2 WebUI</strong><span>${tr("Sign in to continue")}</span></div></div>${error ? `<p class="error">${escapeHtml(error)}</p>` : ""}<div class="field"><label>${tr("Username")}</label><input name="username" autocomplete="username" required /></div><div class="field"><label>${tr("Password")}</label><input name="password" type="password" autocomplete="current-password" required /></div><div class="actions">${button("Sign in", "login", "primary")}</div></form></div>`;
  app.querySelector("form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); try { state.user = await api("/api/auth/login", { method: "POST", body: JSON.stringify(Object.fromEntries(form)) }); await loadInstances(); render(); } catch (failure) { renderLogin(failure.message); } });
}
async function loadInstances() { state.instances = await api("/api/instances"); if (!state.selected && state.instances[0]) state.selected = state.instances[0].id; }
function serverSelect() { return `<select id="server-select">${state.instances.map((item) => `<option value="${item.id}" ${item.id === state.selected ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join("")}</select>`; }
function bindServerSelect() { const select = app.querySelector("#server-select"); if (select) select.addEventListener("change", () => { state.selected = select.value; render(); }); }
async function renderDashboard() {
  const data = await api("/api/dashboard/summary");
  if ((state.modules || []).some((item) => item.id === "visual-map-rotation")) await Promise.all(data.instances.map(async (item) => { try { const rotation = await api(`/api/rotation/${item.instance.id}`); item.estimatedNext = (rotation.queue[0] || rotation.cycle[0])?.title; item.expectedCurrentCommand = rotation.expected_current_command; const expected = expectedStandardMap(item.expectedCurrentCommand); item.mapDrift = Boolean(expected && item.server && item.server.map_name !== expected); } catch { item.estimatedNext = null; item.expectedCurrentCommand = null; item.mapDrift = false; } }));
  const cards = data.instances.length ? data.instances.map((item) => { const server = item.server; const drift = item.mapDrift ? `<p class="error">Map mismatch: panel expected ${escapeHtml(expectedStandardMap(item.expectedCurrentCommand))}, A2S reports ${escapeHtml(server.map_name)}. A plugin or manual command may have changed the map.</p>` : ""; return `<article class="control-card"><div class="server-head"><h3>${escapeHtml(item.instance.name)}</h3><span class="pill ${item.query_status === "online" ? "free" : "occupied"}">${item.query_status}</span></div><p class="stat">${server ? escapeHtml(server.map_name) : "offline"}</p><p class="muted">${server ? `${server.players} players · ${server.bots} bots · ${server.max_players} slots` : `Configured UDP port ${item.instance.game_port}`}</p><p class="muted">Estimated next map: ${escapeHtml(item.estimatedNext || "unknown")}</p>${drift}<p class="muted">RCON ${escapeHtml(item.rcon_status)} · bridge ${escapeHtml(item.bridge_status)}</p></article>`; }).join("") : `<article class="control-card"><h3>No servers yet</h3><p class="muted">Create an instance through the setup wizard or API.</p></article>`;
  const host = data.host; const gib = (value) => value == null ? "n/a" : `${(value / 1073741824).toFixed(1)} GiB`;
  shell(`<div class="section-head"><div><h2>Server overview</h2><p class="muted">A2S status remains independent from lifecycle controls.</p></div></div><div class="grid"><article class="control-card"><h3>Free disk space</h3><p class="stat">${gib(host.disk_free_bytes)}</p><p class="muted">of ${gib(host.disk_total_bytes)}</p></article><article class="control-card"><h3>Available RAM</h3><p class="stat">${gib(host.memory_available_bytes)}</p><p class="muted">of ${gib(host.memory_total_bytes)}</p></article><article class="control-card"><h3>Host load</h3><p class="stat">${host.load_average_1m == null ? "n/a" : host.load_average_1m.toFixed(2)}</p><p class="muted">1 minute load average</p></article><article class="control-card"><h3>Integrations</h3><p class="muted">host-agent ${escapeHtml(data.integrations.host_agent)} · Steam Web API ${escapeHtml(data.integrations.steam_web_api)}</p></article></div><h2>Instances</h2><div class="grid">${cards}</div>`);
}
async function renderInstances() {
  const ports = isAdmin() ? await api("/api/instances/ports?start_port=27015&count=12") : { suggested_port: null };
  const cards = state.instances.map((item) => { const runtime = state.runtime[item.id]; const stats = Array.isArray(runtime?.stats) ? runtime.stats[0] : runtime?.stats; const details = runtime ? `<p class="muted">CPU ${escapeHtml(stats?.CPUPerc ?? stats?.CPU ?? "n/a")} · RAM ${escapeHtml(stats?.MemUsage ?? stats?.MemUsageBytes ?? "n/a")}</p>${runtime.logs ? `<pre class="instance-log">${escapeHtml(runtime.logs)}</pre>` : ""}${runtime.error ? `<p class="error">${escapeHtml(runtime.error)}</p>` : ""}` : `<p class="muted">Runtime metrics have not been loaded yet.</p>`; const operatorActions = canOperate() ? `${button("Start", `start:${item.id}`)}${button("Stop", `stop:${item.id}`)}${button("Apply preset live", `preset:${item.id}:${item.preset}`)}` : ""; const adminActions = isAdmin() ? `${button("Install / validate", `install:${item.id}`)}${button("Clone", `clone:${item.id}`)}${button("Remove entry", `remove:${item.id}`)}${button("Delete files", `purge:${item.id}`)}` : ""; return `<article class="control-card"><div class="server-head"><h3>${escapeHtml(item.name)}</h3><span class="pill">${escapeHtml(item.status)}</span></div><p class="muted">${escapeHtml(item.start_map)} · UDP ${item.game_port} · ${escapeHtml(item.preset)}</p><p class="muted">${escapeHtml(item.server_dir)}</p>${details}<div class="card-actions">${button("Refresh runtime", `runtime:${item.id}`)}${operatorActions}${adminActions}</div></article>`; }).join("");
  const portLines = (ports.ports || []).map((item) => `<span class="pill ${item.available ? "free" : "occupied"}">${item.port}/udp ${item.available ? "available" : "in use"}</span>`).join("");
  const capacity = ports.capacity; const capacityLine = capacity ? `<p class="${capacity.enough_for_recommended_install ? "muted" : "error"}">Disk preflight: ${(capacity.disk_free_bytes / 1073741824).toFixed(1)} GiB free. Valve currently documents roughly 65 GiB per isolated CS2 installation; keep additional space for backups.</p>` : "";
  const createForm = isAdmin() ? `<form id="instance-form" class="control-card form-grid"><div class="wide toolbar">${portLines}</div><div class="wide">${capacityLine}</div><div class="field"><label>Name</label><input name="name" value="CS2 Server" required /></div><div class="field"><label>UDP port</label><input name="game_port" type="number" value="${ports.suggested_port ?? 27015}" required /></div><div class="field"><label>Start map</label><input name="start_map" value="de_dust2" required /></div><div class="field"><label>Preset</label><select name="preset"><option>competitive</option><option>casual</option><option>deathmatch</option><option>workshop</option><option>custom</option></select></div><div class="field"><label>Install source</label><select name="install_source"><option value="steamcmd">Download with SteamCMD</option><option value="import">Import existing files</option><option value="copy">Copy existing files</option><option value="move">Move existing files</option></select></div><div class="field"><label>Source path for import/copy/move</label><input name="source_path" placeholder="/srv/cs2/server" /></div><div class="field"><label>RCON password</label><input name="rcon_password" type="password" required /></div><div class="field"><label>GSLT</label><input name="gslt" type="password" required /></div><label class="check-line"><input name="metamod_enabled" type="checkbox" checked />Install latest MetaMod</label><label class="check-line"><input name="counterstrikesharp_enabled" type="checkbox" checked />Install CounterStrikeSharp with runtime</label><label class="check-line"><input name="bridge_enabled" type="checkbox" checked />Install recommended bridge</label><div class="wide">${button("Create instance", "create-instance", "primary")}</div></form>` : "";
  shell(`<div class="section-head"><div><h2>Isolated servers</h2><p class="muted">Each server owns its directory, port, credentials, and plugin set.</p></div></div>${createForm}<div class="grid">${cards || "<p>No servers configured.</p>"}</div>`);
  app.querySelector("#instance-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.target; const payload = Object.fromEntries(new FormData(form)); payload.game_port = Number(payload.game_port); payload.metamod_enabled = form.metamod_enabled.checked; payload.counterstrikesharp_enabled = form.counterstrikesharp_enabled.checked; payload.bridge_enabled = form.bridge_enabled.checked; try { await api("/api/instances", { method: "POST", body: JSON.stringify(payload) }); await loadInstances(); renderInstances(); } catch (error) { alert(error.message); } });
  app.querySelectorAll("[data-action^='install:'],[data-action^='start:'],[data-action^='stop:']").forEach((element) => element.addEventListener("click", async () => { const [operation, id] = element.dataset.action.split(":"); element.disabled = true; try { const plan = await api(`/api/instances/${id}/plans/${operation}`); const commands = plan.commands.map((item) => `${item.label}\n${item.command}`).join("\n\n"); if (!confirm(`Review ${operation} plan before applying:\n\n${commands}`)) { element.disabled = false; return; } const outcome = await api(`/api/instances/${id}/actions/${operation}`, { method: "POST" }); const unavailable = [...(outcome.prerequisites || []), ...(outcome.bridge ? [outcome.bridge] : [])].filter((item) => item.status === "unavailable"); if (unavailable.length) alert(`Server ${operation} completed, but optional components need attention:\n\n${unavailable.map((item) => `${item.component || "bridge"}: ${item.detail}`).join("\n")}`); await loadInstances(); renderInstances(); } catch (error) { alert(error.message); element.disabled = false; } }));
  app.querySelectorAll("[data-action^='preset:']").forEach((element) => element.addEventListener("click", async () => { const [, id, preset] = element.dataset.action.split(":"); try { await api(`/api/instances/${id}/preset`, { method: "POST", body: JSON.stringify({ preset }) }); alert(`${preset} preset applied live.`); } catch (error) { alert(error.message); } }));
  app.querySelectorAll("[data-action^='runtime:']").forEach((element) => element.addEventListener("click", async () => { const [, id] = element.dataset.action.split(":"); element.disabled = true; const [stats, logs] = await Promise.allSettled([api(`/api/instances/${id}/stats`), api(`/api/instances/${id}/logs`)]); state.runtime[id] = { stats: stats.status === "fulfilled" ? stats.value.stats : null, logs: logs.status === "fulfilled" ? logs.value.stdout : "", error: [stats, logs].filter((item) => item.status === "rejected").map((item) => item.reason.message).join("; ") }; renderInstances(); }));
  app.querySelectorAll("[data-action^='clone:']").forEach((element) => element.addEventListener("click", async () => { const [, id] = element.dataset.action.split(":"); const name = prompt("Clone name:", "CS2 Clone"); const game_port = prompt("Free UDP port:", ports.suggested_port ?? 27015); const rcon_password = prompt("New RCON password:"); const gslt = prompt("New GSLT:"); if (!name || !game_port || !rcon_password || !gslt) return; try { await api(`/api/instances/${id}/clone`, { method: "POST", body: JSON.stringify({ name, game_port: Number(game_port), rcon_password, gslt }) }); await loadInstances(); renderInstances(); } catch (error) { alert(error.message); } }));
  app.querySelectorAll("[data-action^='remove:']").forEach((element) => element.addEventListener("click", async () => { const [, id] = element.dataset.action.split(":"); if (!confirm("Remove this panel entry and preserve all CS2 files?")) return; await api(`/api/instances/${id}`, { method: "DELETE", body: JSON.stringify({ purge_files: false }) }); await loadInstances(); renderInstances(); }));
  app.querySelectorAll("[data-action^='purge:']").forEach((element) => element.addEventListener("click", async () => { const [, id] = element.dataset.action.split(":"); if (prompt("Type DELETE-CS2-FILES to permanently remove this instance directory:") !== "DELETE-CS2-FILES") return; await api(`/api/instances/${id}`, { method: "DELETE", body: JSON.stringify({ purge_files: true, confirmation: "DELETE-CS2-FILES" }) }); await loadInstances(); renderInstances(); }));
}
async function renderConsole() {
  const quick = await api("/api/quick-commands");
  const editor = isAdmin() ? `<form class="toolbar" id="quick-command-form"><input name="label" placeholder="Button label" required /><input name="command" placeholder="bot_quota {count}" required />${button("Save quick command", "save-quick", "primary")}</form>` : "";
  shell(`<div class="toolbar">${serverSelect()}</div><div class="toolbar">${quick.map((item) => `<span>${button(item.label, `quick:${item.id}`)}${isAdmin() && item.custom ? button("Remove", `remove-quick:${item.id}`) : ""}</span>`).join("")}</div><pre class="console-output">${escapeHtml(state.console.join("\n\n") || "RCON console ready.")}</pre><form class="toolbar" id="console-form"><input class="console-input" name="command" placeholder="status" required />${button("Execute", "execute-rcon", "primary")}</form>${editor}`);
  bindServerSelect();
  app.querySelector("#console-form").addEventListener("submit", async (event) => { event.preventDefault(); const instance = selectedInstance(); if (!instance) return; const command = new FormData(event.target).get("command"); try { const response = await api(`/api/instances/${instance.id}/rcon`, { method: "POST", body: JSON.stringify({ command }) }); state.console.push(`> ${command}\n${response.response}`); renderConsole(); } catch (error) { state.console.push(`! ${error.message}`); renderConsole(); } });
  app.querySelectorAll("[data-action^='quick:']").forEach((element) => element.addEventListener("click", () => { const item = quick.find((candidate) => candidate.id === element.dataset.action.split(":")[1]); let command = item.command; item.parameters.forEach((parameter) => { const value = prompt(`${parameter.name}:`, parameter.default); if (value != null) command = command.replace(`{${parameter.name}}`, value); }); app.querySelector(".console-input").value = command; }));
  app.querySelector("#quick-command-form")?.addEventListener("submit", async (event) => { event.preventDefault(); try { await api("/api/quick-commands", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); renderConsole(); } catch (error) { alert(error.message); } });
  app.querySelectorAll("[data-action^='remove-quick:']").forEach((element) => element.addEventListener("click", async () => { await api(`/api/quick-commands/${element.dataset.action.split(":")[1]}`, { method: "DELETE" }); renderConsole(); }));
}
async function renderWorkshop() {
  state.workshop = await api("/api/workshop/maps");
  const status = await api("/api/workshop/status");
  const controls = canOperate();
  const cards = state.workshop.map((item) => `<article class="control-card">${item.preview_url ? `<img class="workshop-preview" src="${escapeHtml(item.preview_url)}" alt="" />` : ""}<h3>${escapeHtml(item.title)}</h3><p class="muted">Workshop ${escapeHtml(item.published_file_id)}</p>${controls ? `<div class="card-actions">${button("Use command", `workshop:${item.published_file_id}`)}<label class="button ghost">Upload preview<input data-upload-workshop="${item.published_file_id}" type="file" accept="image/png,image/jpeg,image/gif,image/webp" hidden /></label></div>` : ""}</article>`).join("");
  const form = controls ? `<form id="workshop-form" class="control-card form-grid"><div class="field wide"><label>Steam Workshop URL or ID</label><input name="source" placeholder="https://steamcommunity.com/sharedfiles/filedetails/?id=..." required /></div><div class="field"><label>Manual title fallback</label><input name="title" placeholder="AWP India" /></div><div class="field"><label>Manual HTTPS preview fallback</label><input name="preview_url" placeholder="https://..." /></div><label class="check-line"><input name="collection" type="checkbox" />Import collection</label><label class="check-line"><input name="cache_preview" type="checkbox" />Cache preview locally</label><div class="wide">${button("Add", "add-workshop", "primary")}</div></form>` : "";
  shell(`<div class="toolbar"><span class="pill">Steam Workshop API: ${escapeHtml(status.steam_workshop_api)}</span></div>${form}<div class="grid">${cards || "<p class='muted'>No Workshop maps added.</p>"}</div>`);
  app.querySelector("#workshop-form")?.addEventListener("submit", async (event) => { event.preventDefault(); try { const form = event.target; await api(form.collection.checked ? "/api/workshop/collections" : "/api/workshop/maps", { method: "POST", body: JSON.stringify({ source: form.source.value, title: form.title.value || null, preview_url: form.preview_url.value || null, cache_preview: form.cache_preview.checked }) }); renderWorkshop(); } catch (error) { alert(error.message); } });
  app.querySelectorAll("[data-action^='workshop:']").forEach((item) => item.addEventListener("click", async () => { const instance = selectedInstance(); if (!instance) { alert("Create a server first."); return; } const id = item.dataset.action.split(":")[1]; const data = await api(`/api/workshop/maps/${id}/command`); if (!confirm(`Switch map now?\n\n${data.command}`)) return; try { await api(`/api/instances/${instance.id}/rcon`, { method: "POST", body: JSON.stringify({ command: data.command }) }); state.console.push(`> ${data.command}`); state.page = "console"; render(); } catch (error) { alert(error.message); } }));
  app.querySelectorAll("[data-upload-workshop]").forEach((item) => item.addEventListener("change", async () => { const file = item.files[0]; if (!file) return; const response = await fetch(`/api/workshop/media/${item.dataset.uploadWorkshop}`, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!response.ok) { const payload = await response.json().catch(() => ({})); alert(payload.detail || "Upload failed"); return; } renderWorkshop(); }));
}
async function renderRotation() {
  const instance = selectedInstance(); if (!instance) { shell("<p>No server configured.</p>"); return; }
  state.rotation = await api(`/api/rotation/${instance.id}`);
  const history = await api(`/api/rotation/${instance.id}/history`);
  const controls = canOperate();
  const cards = state.rotation.cycle.map((item, index) => `<div class="rotation-card" ${controls ? `draggable="true" data-index="${index}"` : ""}><strong>${escapeHtml(item.title)}</strong>${controls ? `<button class="mini-button" data-remove="${index}" type="button">Remove</button>` : ""}</div>`).join("");
  const queue = state.rotation.queue.map((item) => `<div class="rotation-card"><strong>${escapeHtml(item.title)}</strong><span class="muted">one-time</span></div>`).join("");
  const historyCards = history.map((item) => `<div class="control-card"><strong>${escapeHtml(item.created_at)}</strong><p class="muted">${item.maps.map((map) => escapeHtml(map.title)).join(" → ") || "Empty rotation"}</p>${controls ? button("Restore", `restore-rotation:${item.id}`) : ""}</div>`).join("");
  const mapFields = `<select name="kind"><option value="standard">Standard</option><option value="workshop">Workshop</option></select><input name="identifier" placeholder="de_mirage or Workshop ID" required /><input name="title" placeholder="Display name" required />`;
  const importControl = controls ? `<label class="button ghost">Import JSON<input id="rotation-import" type="file" accept="application/json,.json" hidden /></label>` : "";
  const cycleForm = controls ? `<form id="rotation-form" class="toolbar">${mapFields}${button("Add to cycle", "rotation-add", "primary")}</form>` : "";
  const queueForm = controls ? `<form id="queue-form" class="toolbar">${mapFields}${button("Queue map", "queue-add", "primary")}</form>` : "";
  shell(`<div class="toolbar">${serverSelect()}${controls ? button("Skip to next", "next-map", "primary") : ""}${button("Export JSON", "export-rotation")}${importControl}</div><p class="muted">Panel-applied current map command: ${escapeHtml(state.rotation.expected_current_command || "not recorded yet")}</p><div class="grid"><article class="control-card"><h3>Persistent cycle</h3><p class="muted">Drag cards to reorder. This sequence repeats after one-time maps are consumed.</p><div class="rotation-list" id="rotation-list">${cards || "<span class='muted'>Rotation is empty.</span>"}</div>${cycleForm}</article><article class="control-card"><h3>One-time queue</h3><p class="muted">Queue a map for the next transition without changing the persistent cycle.</p><div class="rotation-list">${queue || "<span class='muted'>Queue is empty.</span>"}</div>${queueForm}</article></div><h3>Rotation history</h3><div class="stack">${historyCards || "<p class='muted'>No previous versions yet.</p>"}</div>`);
  bindServerSelect();
  app.querySelector("#rotation-form")?.addEventListener("submit", async (event) => { event.preventDefault(); state.rotation.cycle.push(Object.fromEntries(new FormData(event.target))); await saveRotation(instance.id); renderRotation(); });
  app.querySelector("#queue-form")?.addEventListener("submit", async (event) => { event.preventDefault(); await api(`/api/rotation/${instance.id}/queue`, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); renderRotation(); });
  app.querySelector('[data-action="next-map"]')?.addEventListener("click", async () => { const data = await api(`/api/rotation/${instance.id}/next`, { method: "POST" }); state.console.push(`> ${data.command}`); alert(data.command); renderRotation(); });
  app.querySelector('[data-action="export-rotation"]').addEventListener("click", () => { const blob = new Blob([JSON.stringify({ maps: state.rotation.cycle }, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${instance.slug}-rotation.json`; link.click(); URL.revokeObjectURL(link.href); });
  app.querySelector("#rotation-import")?.addEventListener("change", async (event) => { try { const payload = JSON.parse(await event.target.files[0].text()); await api(`/api/rotation/${instance.id}`, { method: "PUT", body: JSON.stringify(payload) }); renderRotation(); } catch (error) { alert(error.message); } });
  app.querySelectorAll("[data-remove]").forEach((item) => item.addEventListener("click", async () => { state.rotation.cycle.splice(Number(item.dataset.remove), 1); await saveRotation(instance.id); renderRotation(); }));
  app.querySelectorAll("[data-action^='restore-rotation:']").forEach((item) => item.addEventListener("click", async () => { await api(`/api/rotation/${instance.id}/history/${item.dataset.action.split(":")[1]}/restore`, { method: "POST" }); renderRotation(); }));
  let dragged = null; app.querySelectorAll(".rotation-card[data-index]").forEach((card) => { card.addEventListener("dragstart", () => { dragged = Number(card.dataset.index); }); card.addEventListener("dragover", (event) => event.preventDefault()); card.addEventListener("drop", async () => { const target = Number(card.dataset.index); const [item] = state.rotation.cycle.splice(dragged, 1); state.rotation.cycle.splice(target, 0, item); await saveRotation(instance.id); renderRotation(); }); });
}
async function saveRotation(id) { await api(`/api/rotation/${id}`, { method: "PUT", body: JSON.stringify({ maps: state.rotation.cycle }) }); }
async function renderUsers() { const users = await api("/api/users"); const audit = await api("/api/audit?limit=100"); shell(`<div class="section-head"><div><h2>Local accounts</h2><p class="muted">Use viewer for read-only access, operator for daily controls, and admin for configuration changes.</p></div></div><form id="user-form" class="control-card form-grid"><div class="field"><label>Username</label><input name="username" required /></div><div class="field"><label>Password</label><input name="password" type="password" minlength="12" required /></div><div class="field"><label>Role</label><select name="role"><option>viewer</option><option>operator</option><option>admin</option></select></div><div class="wide">${button("Create account", "create-user", "primary")}</div></form><div class="grid">${users.map((user) => `<article class="control-card"><h3>${escapeHtml(user.username)}</h3><p class="muted">${escapeHtml(user.role)}</p></article>`).join("")}</div><h2>Audit log</h2><div class="stack">${audit.map((entry) => `<article class="control-card"><div class="server-head"><strong>${escapeHtml(entry.action)}</strong><span class="muted">${escapeHtml(entry.created_at)}</span></div><p class="muted">${escapeHtml(entry.details)}</p></article>`).join("") || "<p class='muted'>No actions recorded yet.</p>"}</div>`); app.querySelector("#user-form").addEventListener("submit", async (event) => { event.preventDefault(); try { await api("/api/users", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); renderUsers(); } catch (error) { alert(error.message); } }); }
async function renderPlayers() { const instance = selectedInstance(); if (!instance) { shell("<p>No server configured.</p>"); return; } const data = await api(`/api/players/${instance.id}`); shell(`<div class="toolbar">${serverSelect()}<span class="pill">bridge ${escapeHtml(data.status)}</span>${data.steamProfileStatus ? `<span class="pill">Steam Web API ${escapeHtml(data.steamProfileStatus)}</span>` : ""}</div><div class="grid">${data.players.map((player) => `<article class="control-card">${player.steamAvatarUrl ? `<img class="player-avatar" src="${escapeHtml(player.steamAvatarUrl)}" alt="" />` : ""}<div class="server-head"><h3>${escapeHtml(player.name)}</h3><span class="pill">${player.isBot ? "BOT" : `Team ${player.team}`}</span></div><p class="stat">${player.score}</p><p class="muted">score</p>${player.isBot ? "" : `<a class="inline-button button ghost" href="${escapeHtml(player.steamProfileUrl)}" target="_blank" rel="noreferrer">Steam profile</a>`}</article>`).join("") || "<p class='muted'>Bridge snapshot is unavailable or empty.</p>"}</div>`); bindServerSelect(); }
async function renderPlugins() {
  const instance = selectedInstance(); if (!instance) { shell("<p>No server configured.</p>"); return; }
  const plugins = await api(`/api/instances/${instance.id}/plugins`);
  const runtime = await api(`/api/instances/${instance.id}/plugins/runtime-status`);
  const adminActions = isAdmin() ? `${button("Install latest MetaMod", "install-metamod")}${button("Install latest CounterStrikeSharp with runtime", "install-css")}${button("Install built-in bridge", "install-bridge", "primary")}` : "";
  const form = isAdmin() ? `<form id="plugin-form" class="control-card stack"><h3>Install plugin archive or folder</h3><div class="toolbar"><input name="name" placeholder="Plugin name" required /><select name="source_type"><option value="url">HTTPS URL</option><option value="local">Managed local archive / folder</option></select><input name="source" placeholder="https://... or file.zip or extracted-folder" required />${button("Install", "install-plugin", "primary")}</div></form>` : "";
  const cards = plugins.map((plugin) => `<article class="control-card"><div class="server-head"><h3>${escapeHtml(plugin.name)}</h3><span class="pill">${escapeHtml(plugin.status)}</span></div><p class="muted">${escapeHtml(plugin.source)}</p><p class="muted">SHA-256 ${escapeHtml(plugin.checksum || "unknown")}</p>${isAdmin() ? button(plugin.enabled ? "Disable" : "Enable", `toggle-plugin:${plugin.id}:${!plugin.enabled}`) : ""}${canOperate() && plugin.source.startsWith("https://") ? button("Check update", `check-plugin:${plugin.id}`) : ""}</article>`).join("");
  shell(`<div class="toolbar">${serverSelect()}<span class="pill">meta list: ${escapeHtml(runtime.status)}</span>${adminActions}</div><pre class="console-output">${escapeHtml(runtime.output || "No runtime plugin output.")}</pre><p class="muted">Install MetaMod, then CounterStrikeSharp with runtime, then the bridge. Restart the CS2 server and verify <code>meta list</code> through the console.</p>${form}<div class="grid">${cards || "<p class='muted'>No plugins installed.</p>"}</div>`);
  bindServerSelect();
  app.querySelector('[data-action="install-metamod"]')?.addEventListener("click", async () => { try { await api(`/api/instances/${instance.id}/plugins/builtin-metamod`, { method: "POST" }); renderPlugins(); } catch (error) { alert(error.message); } });
  app.querySelector('[data-action="install-css"]')?.addEventListener("click", async () => { try { await api(`/api/instances/${instance.id}/plugins/builtin-counterstrikesharp`, { method: "POST" }); renderPlugins(); } catch (error) { alert(error.message); } });
  app.querySelector('[data-action="install-bridge"]')?.addEventListener("click", async () => { try { await api(`/api/instances/${instance.id}/plugins/builtin-bridge`, { method: "POST" }); renderPlugins(); } catch (error) { alert(error.message); } });
  app.querySelector("#plugin-form")?.addEventListener("submit", async (event) => { event.preventDefault(); try { await api(`/api/instances/${instance.id}/plugins`, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); renderPlugins(); } catch (error) { alert(error.message); } });
  app.querySelectorAll("[data-action^='toggle-plugin:']").forEach((item) => item.addEventListener("click", async () => { const [, id, enabled] = item.dataset.action.split(":"); await api(`/api/instances/${instance.id}/plugins/${id}`, { method: "PUT", body: JSON.stringify({ enabled: enabled === "true" }) }); renderPlugins(); }));
  app.querySelectorAll("[data-action^='check-plugin:']").forEach((item) => item.addEventListener("click", async () => { try { const result = await api(`/api/instances/${instance.id}/plugins/${item.dataset.action.split(":")[1]}/update-check`); alert(result.update_available ? "Plugin source has changed. Review and reinstall it when ready." : "Installed archive matches the source URL."); } catch (error) { alert(error.message); } }));
}
async function renderMaintenance() {
  const instance = selectedInstance(); if (!instance) { shell("<p>No server configured.</p>"); return; }
  const policy = await api(`/api/instances/${instance.id}/maintenance`);
  const backups = await api(`/api/instances/${instance.id}/backups`);
  const notice = policy.next_run_at ? `<article class="control-card"><h3>Scheduled restart notice</h3><p class="stat">${escapeHtml(new Date(policy.next_run_at).toLocaleString())}</p><p class="muted">Show a warning ${policy.notify_before_minutes} minutes before the planned restart. Player-aware defer remains active when enabled.</p></article>` : "";
  const policyForm = isAdmin() ? `<form id="maintenance-form" class="control-card form-grid"><div class="field"><label>Restart every minutes</label><input name="restart_every_minutes" type="number" min="5" value="${policy.restart_every_minutes ?? ""}" /></div><div class="field"><label>Notify before minutes</label><input name="notify_before_minutes" type="number" min="0" value="${policy.notify_before_minutes}" /></div><div class="field"><label>Maximum defer minutes</label><input name="max_defer_minutes" type="number" min="0" value="${policy.max_defer_minutes}" /></div><label class="check-line"><input name="update_before_restart" type="checkbox" ${policy.update_before_restart ? "checked" : ""} />Update before restart</label><label class="check-line"><input name="defer_while_players_online" type="checkbox" ${policy.defer_while_players_online ? "checked" : ""} />Defer while players are online</label><label class="check-line"><input name="backup_before_update" type="checkbox" ${policy.backup_before_update ? "checked" : ""} />Backup before update</label><div class="wide">${button("Save policy", "save-maintenance", "primary")}</div></form>` : "";
  const backupCards = backups.map((backup) => `<div class="control-card"><strong>${escapeHtml(backup.name)}</strong><p class="muted">${backup.size} bytes</p>${isAdmin() ? button("Restore", `restore-backup:${backup.name}`) : ""}</div>`).join("");
  shell(`<div class="toolbar">${serverSelect()}${canOperate() ? button("Create backup", "create-backup", "primary") : ""}${isAdmin() ? button("Run maintenance now", "run-maintenance") : ""}</div>${notice}${policyForm}<h3>Backups</h3><div class="stack">${backupCards || "<p class='muted'>No backups yet.</p>"}</div>`);
  bindServerSelect();
  app.querySelector('[data-action="create-backup"]')?.addEventListener("click", async () => { await api(`/api/instances/${instance.id}/backups`, { method: "POST" }); renderMaintenance(); });
  app.querySelector('[data-action="run-maintenance"]')?.addEventListener("click", async () => { if (!confirm("Run maintenance now? The CS2 instance may stop, update, and restart according to the saved policy.")) return; const result = await api(`/api/instances/${instance.id}/maintenance/run`, { method: "POST" }); alert(`Maintenance status: ${result.status}`); renderMaintenance(); });
  app.querySelectorAll("[data-action^='restore-backup:']").forEach((item) => item.addEventListener("click", async () => { const name = item.dataset.action.slice("restore-backup:".length); if (!confirm(`Restore ${name}? Current config and addon files with matching paths will be overwritten.`)) return; await api(`/api/instances/${instance.id}/backups/${encodeURIComponent(name)}/restore`, { method: "POST" }); alert("Backup restored."); }));
  app.querySelector("#maintenance-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.target; await api(`/api/instances/${instance.id}/maintenance`, { method: "PUT", body: JSON.stringify({ restart_every_minutes: form.restart_every_minutes.value ? Number(form.restart_every_minutes.value) : null, notify_before_minutes: Number(form.notify_before_minutes.value), max_defer_minutes: Number(form.max_defer_minutes.value), update_before_restart: form.update_before_restart.checked, defer_while_players_online: form.defer_while_players_online.checked, backup_before_update: form.backup_before_update.checked }) }); renderMaintenance(); });
}
async function renderConfig() {
  const instance = selectedInstance(); if (!instance) { shell("<p>No server configured.</p>"); return; }
  const data = await api(`/api/instances/${instance.id}/config?path=${encodeURIComponent(state.configPath)}`);
  const configActions = isAdmin() ? `${button("Preview diff", "preview-config")}${button("Apply with backup", "apply-config", "primary")}` : "";
  shell(`<div class="toolbar">${serverSelect()}<input id="config-path" list="config-paths" value="${escapeHtml(data.path)}" placeholder="game/csgo/cfg/server.cfg" /><datalist id="config-paths"><option value="game/csgo/cfg/server.cfg"></option><option value="game/csgo/mapcycle.txt"></option></datalist>${button("Load file", "load-config")}</div><article class="control-card"><h3>${escapeHtml(data.path)}</h3><p class="muted">Preview the diff before writing configuration files. A focused backup is created when changes are applied.</p><textarea class="config-editor" id="config-content" ${isAdmin() ? "" : "readonly"}>${escapeHtml(data.content)}</textarea><div class="card-actions">${configActions}</div><pre class="console-output" id="config-diff">No preview yet.</pre></article>`);
  bindServerSelect();
  app.querySelector('[data-action="load-config"]').addEventListener("click", () => { state.configPath = app.querySelector("#config-path").value; renderConfig(); });
  async function update(apply) { const path = app.querySelector("#config-path").value; const response = await api(`/api/instances/${instance.id}/config?path=${encodeURIComponent(path)}`, { method: "PUT", body: JSON.stringify({ content: app.querySelector("#config-content").value, apply }) }); state.configPath = response.path; app.querySelector("#config-diff").textContent = response.diff || "No differences."; }
  app.querySelector('[data-action="preview-config"]')?.addEventListener("click", () => update(false));
  app.querySelector('[data-action="apply-config"]')?.addEventListener("click", () => update(true));
}
function renderModule() { const module = (state.modules || []).find((item) => `module:${item.id}` === state.page); if (!module?.ui_path) { shell("<p>Module UI is unavailable.</p>"); return; } shell(`<iframe class="module-frame" src="${escapeHtml(module.ui_path)}" sandbox="allow-forms allow-scripts allow-same-origin"></iframe>`); }
async function render() { try { if (!state.user) state.user = await api("/api/auth/me"); if (!state.modules) state.modules = await api("/api/modules"); if (!isPageVisible(state.page)) state.page = "instances"; await loadInstances(); state.notices = await api("/api/instances/notices"); if (state.page === "dashboard") return renderDashboard(); if (state.page === "instances") return renderInstances(); if (state.page === "console") return renderConsole(); if (state.page === "workshop") return renderWorkshop(); if (state.page === "rotation") return renderRotation(); if (state.page === "plugins") return renderPlugins(); if (state.page === "players") return renderPlayers(); if (state.page === "config") return renderConfig(); if (state.page === "maintenance") return renderMaintenance(); if (state.page === "users") return renderUsers(); if (state.page.startsWith("module:")) return renderModule(); } catch (error) { if (error.message !== "Authentication required") alert(error.message); } }
async function refreshNotices() { try { if (!state.user) return; const notices = await api("/api/instances/notices"); if (JSON.stringify(notices) !== JSON.stringify(state.notices)) { state.notices = notices; render(); } } catch (error) { if (error.message !== "Authentication required") console.error(error); } }
render();
setInterval(refreshNotices, 30000);
